create table if not exists public.guests (
  id bigint generated by default as identity primary key,
  guest_name text not null,
  title text,
  phone text not null,
  group_name text,
  status text not null default 'pending',
  image_url text,
  whatsapp_status text not null default 'pending',
  sent_at timestamptz,
  error_message text,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists guests_status_idx on public.guests(status);
create index if not exists guests_whatsapp_status_idx on public.guests(whatsapp_status);

insert into storage.buckets (id, name, public)
values ('invitation-images', 'invitation-images', true)
on conflict (id) do nothing;
